In [1]:
import torch
import numpy as np

In [2]:
input = torch.tensor(np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]))
l1 = input.view(1, 1, 4, 4)
print(l1.size())
print(l1)

torch.Size([1, 1, 4, 4])
tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]]])


In [3]:
print("Channel 0:")
print(l1[0][0].data.cpu().numpy())

Channel 0:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
l2 = input.view(1, 2, 1, 8)
print(l2)

tensor([[[[ 0,  1,  2,  3,  4,  5,  6,  7]],

         [[ 8,  9, 10, 11, 12, 13, 14, 15]]]])


In [5]:
l3 = l2.permute(0, 3, 2, 1)
print(l3.size())
print(l3)

torch.Size([1, 8, 1, 2])
tensor([[[[ 0,  8]],

         [[ 1,  9]],

         [[ 2, 10]],

         [[ 3, 11]],

         [[ 4, 12]],

         [[ 5, 13]],

         [[ 6, 14]],

         [[ 7, 15]]]])


In [6]:
l4 = l3.contiguous().view(2, 2, 1, 4)
print(l4)

tensor([[[[ 0,  8,  1,  9]],

         [[ 2, 10,  3, 11]]],


        [[[ 4, 12,  5, 13]],

         [[ 6, 14,  7, 15]]]])


In [7]:
l5 = l4.permute(0, 3, 2, 1)
print(l5.size())
print(l5)

torch.Size([2, 4, 1, 2])
tensor([[[[ 0,  2]],

         [[ 8, 10]],

         [[ 1,  3]],

         [[ 9, 11]]],


        [[[ 4,  6]],

         [[12, 14]],

         [[ 5,  7]],

         [[13, 15]]]])


In [8]:
l6 = l5.contiguous().view(1, 4, 2, 2)
print(l6)

tensor([[[[ 0,  2],
          [ 8, 10]],

         [[ 1,  3],
          [ 9, 11]],

         [[ 4,  6],
          [12, 14]],

         [[ 5,  7],
          [13, 15]]]])


In [9]:
print("Channel 0:")
print(l6[0][0].data.cpu().numpy())

Channel 0:
[[ 0  2]
 [ 8 10]]


In [10]:
print("Channel 1:")
print(l6[0][1].data.cpu().numpy())

Channel 1:
[[ 1  3]
 [ 9 11]]


In [11]:
print("Channel 2:")
print(l6[0][2].data.cpu().numpy())

Channel 2:
[[ 4  6]
 [12 14]]


In [12]:
print("Channel 3:")
print(l6[0][3].data.cpu().numpy())

Channel 3:
[[ 5  7]
 [13 15]]
