In [1]:
import torch
import numpy as np

In [2]:
input = torch.tensor(np.array([1,2,3,4,5,6,7,8]))
l1 = input.view(1, 2, 2, 2)
print(l1.size())
print(l1)

torch.Size([1, 2, 2, 2])
tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]])


In [3]:
print("Channel 0:")
print(l1[0][0].data.cpu().numpy())

Channel 0:
[[1 2]
 [3 4]]


In [4]:
print("Channel 1:")
print(l1[0][1].data.cpu().numpy())

Channel 1:
[[5 6]
 [7 8]]


In [5]:
l2 = l1.permute(0, 1, 3, 2)
print(l2.size())
print(l2)

torch.Size([1, 2, 2, 2])
tensor([[[[1, 3],
          [2, 4]],

         [[5, 7],
          [6, 8]]]])


In [6]:
print("Channel 0:")
print(l2[0][0].data.cpu().numpy())

Channel 0:
[[1 3]
 [2 4]]


In [7]:
print("Channel 1:")
print(l2[0][1].data.cpu().numpy())

Channel 1:
[[5 7]
 [6 8]]
