In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.0.0-rc1


In [2]:
sess = tf.compat.v1.InteractiveSession()

In [3]:
input = tf.constant(np.arange(16.).reshape(1,1,4,4))
input = tf.transpose(input, [0, 2, 3, 1])
print(input.get_shape())

(1, 4, 4, 1)


In [4]:
block_shape = [2,2]
pad = [[0, 0], [0, 0]]
l1 = tf.space_to_batch(input, paddings=pad, block_shape=block_shape)

In [5]:
#print(l1)

In [6]:
out = tf.transpose(l1, [0, 3, 1, 2])
#print(out.get_shape())
print(out)

tf.Tensor(
[[[[ 0.  2.]
   [ 8. 10.]]]


 [[[ 1.  3.]
   [ 9. 11.]]]


 [[[ 4.  6.]
   [12. 14.]]]


 [[[ 5.  7.]
   [13. 15.]]]], shape=(4, 1, 2, 2), dtype=float64)
