In [1]:
import tensorflow as tf
import numpy as np
%load_ext wurlitzer

print(tf.__version__)

2.0.0-rc1


In [2]:
sess = tf.compat.v1.InteractiveSession()

2020-03-09 19:06:10.404397: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-09 19:06:10.425975: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1992000000 Hz
2020-03-09 19:06:10.427603: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x587b0f0 executing computations on platform Host. Devices:
2020-03-09 19:06:10.427689: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version


In [3]:
tensor = tf.range(10)
tf.print(tensor)

[0 1 2 ... 7 8 9]


In [4]:
input = tf.constant(np.arange(256.).reshape(1,4,8,8))
print(input)
tf.print(input)

tf.Tensor(
[[[[  0.   1.   2.   3.   4.   5.   6.   7.]
   [  8.   9.  10.  11.  12.  13.  14.  15.]
   [ 16.  17.  18.  19.  20.  21.  22.  23.]
   [ 24.  25.  26.  27.  28.  29.  30.  31.]
   [ 32.  33.  34.  35.  36.  37.  38.  39.]
   [ 40.  41.  42.  43.  44.  45.  46.  47.]
   [ 48.  49.  50.  51.  52.  53.  54.  55.]
   [ 56.  57.  58.  59.  60.  61.  62.  63.]]

  [[ 64.  65.  66.  67.  68.  69.  70.  71.]
   [ 72.  73.  74.  75.  76.  77.  78.  79.]
   [ 80.  81.  82.  83.  84.  85.  86.  87.]
   [ 88.  89.  90.  91.  92.  93.  94.  95.]
   [ 96.  97.  98.  99. 100. 101. 102. 103.]
   [104. 105. 106. 107. 108. 109. 110. 111.]
   [112. 113. 114. 115. 116. 117. 118. 119.]
   [120. 121. 122. 123. 124. 125. 126. 127.]]

  [[128. 129. 130. 131. 132. 133. 134. 135.]
   [136. 137. 138. 139. 140. 141. 142. 143.]
   [144. 145. 146. 147. 148. 149. 150. 151.]
   [152. 153. 154. 155. 156. 157. 158. 159.]
   [160. 161. 162. 163. 164. 165. 166. 167.]
   [168. 169. 170. 171. 172. 173. 174. 1

In [9]:
block_shape = [2,2]
pad = [[0, 0], [0, 0]]
l1 = tf.space_to_batch(input, paddings=pad, block_shape=block_shape)

In [11]:
print(l1)
tf.print(l1)

tf.Tensor(
[[[[  0.   1.   2.   3.   4.   5.   6.   7.]
   [ 16.  17.  18.  19.  20.  21.  22.  23.]
   [ 32.  33.  34.  35.  36.  37.  38.  39.]
   [ 48.  49.  50.  51.  52.  53.  54.  55.]]

  [[128. 129. 130. 131. 132. 133. 134. 135.]
   [144. 145. 146. 147. 148. 149. 150. 151.]
   [160. 161. 162. 163. 164. 165. 166. 167.]
   [176. 177. 178. 179. 180. 181. 182. 183.]]]


 [[[  8.   9.  10.  11.  12.  13.  14.  15.]
   [ 24.  25.  26.  27.  28.  29.  30.  31.]
   [ 40.  41.  42.  43.  44.  45.  46.  47.]
   [ 56.  57.  58.  59.  60.  61.  62.  63.]]

  [[136. 137. 138. 139. 140. 141. 142. 143.]
   [152. 153. 154. 155. 156. 157. 158. 159.]
   [168. 169. 170. 171. 172. 173. 174. 175.]
   [184. 185. 186. 187. 188. 189. 190. 191.]]]


 [[[ 64.  65.  66.  67.  68.  69.  70.  71.]
   [ 80.  81.  82.  83.  84.  85.  86.  87.]
   [ 96.  97.  98.  99. 100. 101. 102. 103.]
   [112. 113. 114. 115. 116. 117. 118. 119.]]

  [[192. 193. 194. 195. 196. 197. 198. 199.]
   [208. 209. 210. 211. 212. 2