In [1]:
import tensorflow as tf
import numpy as np
%load_ext wurlitzer

In [2]:
sess = tf.InteractiveSession()

2020-03-09 18:24:43.222807: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-09 18:24:43.249558: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1992000000 Hz
2020-03-09 18:24:43.251098: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x599cdb0 executing computations on platform Host. Devices:
2020-03-09 18:24:43.251157: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>


In [3]:
def print_tsr(tsr):
    with sess.as_default():
        print_op = tf.print(tsr)
        with tf.control_dependencies([print_op]):
            out = tf.add(tsr, tsr)
            sess.run(out)
    

In [4]:
#input = np.array([1,2,3,4,5,6,7,8]).reshape([1, 2, 2, 2])
input = tf.constant(np.arange(256.).reshape(1,4,8,8))
print(input)
print_tsr(input)

Tensor("Const:0", shape=(1, 4, 8, 8), dtype=float64)


[[[[0 1 2 ... 5 6 7]
   [8 9 10 ... 13 14 15]
   [16 17 18 ... 21 22 23]
   ...
   [40 41 42 ... 45 46 47]
   [48 49 50 ... 53 54 55]
   [56 57 58 ... 61 62 63]]

  [[64 65 66 ... 69 70 71]
   [72 73 74 ... 77 78 79]
   [80 81 82 ... 85 86 87]
   ...
   [104 105 106 ... 109 110 111]
   [112 113 114 ... 117 118 119]
   [120 121 122 ... 125 126 127]]

  [[128 129 130 ... 133 134 135]
   [136 137 138 ... 141 142 143]
   [144 145 146 ... 149 150 151]
   ...
   [168 169 170 ... 173 174 175]
   [176 177 178 ... 181 182 183]
   [184 185 186 ... 189 190 191]]

  [[192 193 194 ... 197 198 199]
   [200 201 202 ... 205 206 207]
   [208 209 210 ... 213 214 215]
   ...
   [232 233 234 ... 237 238 239]
   [240 241 242 ... 245 246 247]
   [248 249 250 ... 253 254 255]]]]


In [5]:
block_size = 2
pad = [[0, 0], [0, 0]]
l1 = tf.space_to_batch(input, pad, block_size=block_size)

In [6]:
print(l1)
print_tsr(l1)

Tensor("SpaceToBatchND:0", shape=(4, 2, 4, 8), dtype=float64)


[[[[0 1 2 ... 5 6 7]
   [16 17 18 ... 21 22 23]
   [32 33 34 ... 37 38 39]
   [48 49 50 ... 53 54 55]]

  [[128 129 130 ... 133 134 135]
   [144 145 146 ... 149 150 151]
   [160 161 162 ... 165 166 167]
   [176 177 178 ... 181 182 183]]]


 [[[8 9 10 ... 13 14 15]
   [24 25 26 ... 29 30 31]
   [40 41 42 ... 45 46 47]
   [56 57 58 ... 61 62 63]]

  [[136 137 138 ... 141 142 143]
   [152 153 154 ... 157 158 159]
   [168 169 170 ... 173 174 175]
   [184 185 186 ... 189 190 191]]]


 [[[64 65 66 ... 69 70 71]
   [80 81 82 ... 85 86 87]
   [96 97 98 ... 101 102 103]
   [112 113 114 ... 117 118 119]]

  [[192 193 194 ... 197 198 199]
   [208 209 210 ... 213 214 215]
   [224 225 226 ... 229 230 231]
   [240 241 242 ... 245 246 247]]]


 [[[72 73 74 ... 77 78 79]
   [88 89 90 ... 93 94 95]
   [104 105 106 ... 109 110 111]
   [120 121 122 ... 125 126 127]]

  [[200 201 202 ... 205 206 207]
   [216 217 218 ... 221 222 223]
   [232 233 234 ... 237 238 239]
   [248 249 250 ... 253 254 255]]]]
