In [1]:
import tensorflow as tf
import numpy as np
%load_ext wurlitzer

In [2]:
sess = tf.InteractiveSession()

2020-03-08 19:44:37.406263: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-08 19:44:37.437134: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1992000000 Hz
2020-03-08 19:44:37.439188: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5ac1170 executing computations on platform Host. Devices:
2020-03-08 19:44:37.439268: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>


In [9]:
t = tf.constant(np.arange(32.).reshape(1,4,4,2))
print(t)
with sess.as_default():
    print_op = tf.print(t)
    with tf.control_dependencies([print_op]):
        out = tf.add(t, t)
        sess.run(out)

Tensor("Const_2:0", shape=(1, 4, 4, 2), dtype=float64)


[[[[0 1]
   [2 3]
   [4 5]
   [6 7]]

  [[8 9]
   [10 11]
   [12 13]
   [14 15]]

  [[16 17]
   [18 19]
   [20 21]
   [22 23]]

  [[24 25]
   [26 27]
   [28 29]
   [30 31]]]]


In [4]:
block_size = 2
input = np.array([1,2,3,4,5,6,7,8]).reshape([1, 4, 4, 2])
crops = np.zeros((2, 2), dtype=np.int32)
pad = [[0, 0], [0, 0]]

In [5]:
l1 = tf.space_to_batch(input, pad, block_size=block_size)

In [6]:
sess = tf.Session()
with sess.as_default():
    print_op = tf.print(l1)
    with tf.control_dependencies([print_op]):
        out = tf.add(l1, l1)
        sess.run(out)


[[[[1 2]]]


 [[[3 4]]]


 [[[5 6]]]


 [[[7 8]]]]


In [7]:
print(l1)

Tensor("SpaceToBatchND:0", shape=(4, 1, 1, 2), dtype=int64)
